-- Luxury Registry catalog + order schema
-- Apply to the dedicated Luxury Registry Supabase project.

create table if not exists public.products (
  id text primary key,
  handle text not null unique,
  title text not null,
  brand text not null,
  product_type text not null,
  department text not null check (department in ('Tops','Outerwear','Denim','Footwear','Bags')),
  price numeric(10,2) not null check (price >= 0),
  compare_at numeric(10,2),
  colors text not null default '',
  short_description text not null default '',
  image_file text,
  image_url text,
  sizes text[],
  availability text not null default 'preorder'
    check (availability in ('in stock','out of stock','preorder')),
  verified boolean not null default false,
  channel_ready boolean not null default false,
  buyable boolean not null default false,
  gtin text,
  mpn text,
  identifier_exists boolean not null default false,
  catalog_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_handle_idx on public.products(handle);
create index if not exists products_department_idx on public.products(department);
create index if not exists products_brand_idx on public.products(brand);
create index if not exists products_channel_ready_idx on public.products(channel_ready)
  where channel_ready = true;

alter table public.products enable row level security;

drop policy if exists "Public can read visible catalog products" on public.products;
create policy "Public can read visible catalog products"
on public.products
for select
to anon, authenticated
using (catalog_visible = true);

grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  stripe_session_id text not null unique,
  registry_id text references public.products(id),
  product_title text,
  size text,
  quantity integer not null default 1 check (quantity > 0),
  amount_total integer,
  currency text,
  payment_status text,
  customer_email text,
  customer_name text,
  shipping_name text,
  shipping_address jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- No anon/authenticated policies are created for orders.
-- Server-side writes should use the Supabase service-role key only.
revoke all on public.orders from anon, authenticated;
